unit unit_LangSignature;

// Signature verification for language catalogs.
//
// Catalogs for locales the project does not ship must arrive as a pair --
// <code>.json and <code>.json.sig -- where the .sig is 64 raw bytes (r||s) of
// an ECDSA P-256 signature over the catalog's exact bytes. No canonicalisation
// is involved anywhere: we sign bytes, not documents.
//
// This is deliberately NOT security. The repository is public, so anyone may
// delete this check and rebuild. What it removes is the casual path: dropping
// a file into a folder becomes running a patched binary from a stranger, and
// that difference is the entire point. See
// docs/superpowers/specs/2026-08-11-signed-lang-catalogs-design.md.
//
// Crypto lives only in this unit. unit_Localization knows nothing beyond the
// one function below.

interface

// True only when <ACatalogFileName>.sig exists, is exactly 64 bytes, and
// verifies. Never raises: it runs before the splash screen exists, where an
// exception dialog is not an acceptable outcome.
function VerifyCatalogSignature(const ACatalogFileName: string): Boolean;

implementation

uses
  Winapi.Windows,
  System.SysUtils,
  System.IOUtils,
  System.Hash;

const
  // ECDSA P-256 public key, X||Y. Generated by tools/lang/keygen.js.
  // The matching private key is held by the maintainer and never ships.
  LANG_PUBLIC_KEY: array [0 .. 63] of Byte = (
    $9D, $E5, $42, $56, $67, $B4, $D9, $4B,
    $07, $80, $CA, $5D, $E9, $8A, $DB, $89,
    $33, $88, $7F, $E9, $3D, $91, $5B, $C9,
    $99, $DE, $77, $2D, $6D, $AE, $52, $E8,
    $E9, $15, $5C, $6A, $53, $FC, $F3, $54,
    $8A, $F1, $CE, $2A, $79, $FE, $C8, $41,
    $9D, $44, $B5, $81, $DF, $88, $22, $8C,
    $7E, $1E, $B3, $4C, $5B, $F4, $E2, $42
  );

  SIGNATURE_SIZE = 64;
  BCRYPT_ECDSA_P256_ALGORITHM = 'ECDSA_P256';
  BCRYPT_ECCPUBLIC_BLOB = 'ECCPUBLICBLOB';
  BCRYPT_ECDSA_PUBLIC_P256_MAGIC = $31534345; // 'ECS1'
  STATUS_SUCCESS = 0;

type
  // Declared here rather than relying on Winapi.Windows: the alias has moved
  // between RTL versions, and this unit must not depend on which one is in
  // scope.
  TNTStatus = LongInt;
  TBCryptHandle = THandle;

  BCRYPT_ECCKEY_BLOB = record
    dwMagic: ULONG;
    cbKey: ULONG;
  end;

// Delay-loaded on purpose. bcrypt.dll has shipped with Windows since Vista,
// but a static import turns its absence into an application that will not
// start. Delayed, the absence degrades to "no file catalog can be verified",
// and the languages in the exe keep working -- which is how every other
// failure in this feature behaves.
function BCryptOpenAlgorithmProvider(out phAlgorithm: TBCryptHandle;
  pszAlgId, pszImplementation: PWideChar; dwFlags: ULONG): TNTStatus;
  stdcall; external 'bcrypt.dll' delayed;

function BCryptCloseAlgorithmProvider(hAlgorithm: TBCryptHandle;
  dwFlags: ULONG): TNTStatus; stdcall; external 'bcrypt.dll' delayed;

function BCryptImportKeyPair(hAlgorithm, hImportKey: TBCryptHandle;
  pszBlobType: PWideChar; out phKey: TBCryptHandle; pbInput: PByte;
  cbInput, dwFlags: ULONG): TNTStatus; stdcall; external 'bcrypt.dll' delayed;

function BCryptDestroyKey(hKey: TBCryptHandle): TNTStatus;
  stdcall; external 'bcrypt.dll' delayed;

function BCryptVerifySignature(hKey: TBCryptHandle; pPaddingInfo: Pointer;
  pbHash: PByte; cbHash: ULONG; pbSignature: PByte;
  cbSignature, dwFlags: ULONG): TNTStatus; stdcall; external 'bcrypt.dll' delayed;

// BCRYPT_ECCPUBLIC_BLOB is an 8-byte header followed by the raw X||Y that
// LANG_PUBLIC_KEY already holds.
function PublicKeyBlob: TBytes;
var
  Header: BCRYPT_ECCKEY_BLOB;
begin
  Header.dwMagic := BCRYPT_ECDSA_PUBLIC_P256_MAGIC;
  Header.cbKey := 32;
  SetLength(Result, SizeOf(Header) + Length(LANG_PUBLIC_KEY));
  Move(Header, Result[0], SizeOf(Header));
  Move(LANG_PUBLIC_KEY[0], Result[SizeOf(Header)], Length(LANG_PUBLIC_KEY));
end;

function Sha256(const AData: TBytes): TBytes;
var
  Hash: THashSHA2;
begin
  Hash := THashSHA2.Create(THashSHA2.TSHA2Version.SHA256);
  Hash.Update(AData);
  Result := Hash.HashAsBytes;
end;

function VerifyBytes(const AData, ASignature: TBytes): Boolean;
var
  hAlg, hKey: TBCryptHandle;
  Blob, Digest: TBytes;
begin
  Result := False;
  hAlg := 0;
  try
    if BCryptOpenAlgorithmProvider(hAlg, PWideChar(BCRYPT_ECDSA_P256_ALGORITHM),
      nil, 0) <> STATUS_SUCCESS then
      Exit;
    try
      Blob := PublicKeyBlob;
      hKey := 0;
      if BCryptImportKeyPair(hAlg, 0, PWideChar(BCRYPT_ECCPUBLIC_BLOB), hKey,
        @Blob[0], Length(Blob), 0) <> STATUS_SUCCESS then
        Exit;
      try
        Digest := Sha256(AData);
        Result := BCryptVerifySignature(hKey, nil, @Digest[0], Length(Digest),
          @ASignature[0], Length(ASignature), 0) = STATUS_SUCCESS;
      finally
        BCryptDestroyKey(hKey);
      end;
    finally
      BCryptCloseAlgorithmProvider(hAlg, 0);
    end;
  except
    // A delay-loaded import that cannot resolve raises here. Treat it as
    // "cannot verify", which means "do not load", not "crash".
    on E: Exception do
      Result := False;
  end;
end;

function VerifyCatalogSignature(const ACatalogFileName: string): Boolean;
var
  SigFileName: string;
  Data, Signature: TBytes;
begin
  Result := False;
  try
    SigFileName := ACatalogFileName + '.sig';
    if not FileExists(SigFileName) then
      Exit;

    Signature := TFile.ReadAllBytes(SigFileName);
    // Checked before any crypto runs: a wrong-sized .sig is not a signature
    // this scheme ever produces, and @ASignature[0] on an empty array faults.
    if Length(Signature) <> SIGNATURE_SIZE then
      Exit;

    Data := TFile.ReadAllBytes(ACatalogFileName);
    if Length(Data) = 0 then
      Exit;

    Result := VerifyBytes(Data, Signature);
  except
    on E: Exception do
      Result := False;
  end;
end;

end.
