'use strict';

// Generates langtest_fixture.res: embedded catalogs that only the test harness
// links, covering the two ways an embedded catalog can be illegitimate.
//
// Neither case needs the signing key -- that is the point. A catalog with no
// signature resource and a catalog with 64 bytes of nonsense are both things
// an attacker can produce with a resource editor, and both must be refused.
// The positive case is the real LANG_EN/LANG_BG the harness already links.
//
//   LANG_XX  catalog, no LANG_XX_SIG        -> must not be offered
//   LANG_ZZ  catalog + LANG_ZZ_SIG of junk  -> must not be offered
//
// Usage: node tools/lang/tests/make_fixture_res.js <path-to-brcc32.exe>
// Exit code: 0 = written, 1 = brcc32 failed.

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const HERE = __dirname;
const FIXTURE_DIR = path.join(HERE, 'fixture');
const RC_PATH = path.join(HERE, 'langtest_fixture.rc');
const RES_PATH = path.join(HERE, 'langtest_fixture.res');

const brcc32 = process.argv[2];
if (!brcc32 || !fs.existsSync(brcc32)) {
  console.error('usage: node make_fixture_res.js <path-to-brcc32.exe>');
  process.exit(1);
}

// Deliberately translated, not identity: an identity catalog produces an empty
// index and would be dropped for that reason instead of the one under test.
function catalog(code, name) {
  return {
    locale: code,
    name,
    strings: {
      unit_probe_Author: { source: 'Автор', target: `[${code}]Автор` },
      unit_probe_Title: { source: 'Назва', target: `[${code}]Назва` },
    },
    dfm: {},
  };
}

fs.mkdirSync(FIXTURE_DIR, { recursive: true });

const xx = Buffer.from(JSON.stringify(catalog('xx', 'Unsigned'), null, 2), 'utf8');
const zz = Buffer.from(JSON.stringify(catalog('zz', 'Badly signed'), null, 2), 'utf8');
fs.writeFileSync(path.join(FIXTURE_DIR, 'xx.json'), xx);
fs.writeFileSync(path.join(FIXTURE_DIR, 'zz.json'), zz);

// 64 bytes, so the length check passes and the verifier is actually reached.
// Fixed, not random: a failing test should reproduce byte for byte.
fs.writeFileSync(path.join(FIXTURE_DIR, 'zz.json.sig'),
  Buffer.alloc(64, 0xA5));

const rc = [
  '// Generated by tools/lang/tests/make_fixture_res.js -- do not edit.',
  '// Test-only catalogs. Never linked into MyHomeLib.exe.',
  '',
  'LANG_XX RCDATA "fixture\\xx.json"',
  'LANG_ZZ RCDATA "fixture\\zz.json"',
  'LANG_ZZ_SIG RCDATA "fixture\\zz.json.sig"',
  '',
].join('\r\n');
fs.writeFileSync(RC_PATH, rc, 'utf8');

const r = spawnSync(brcc32, [`-fo${RES_PATH}`, RC_PATH], { encoding: 'utf8' });
if (r.status !== 0) {
  console.error(`brcc32 failed: ${r.stdout || ''}${r.stderr || ''}`);
  process.exit(1);
}
console.log('langtest_fixture.res written: LANG_XX, LANG_ZZ, LANG_ZZ_SIG');
