'use strict';

// Generates Program/lang.rc, which links the catalogs we ship into the exe.
//
// Only uk and en are ever embedded: they are the languages the project ships,
// and being inside the binary is what makes them unreplaceable by a file in
// Lang\. Any other locale is a community catalog and must be signed.
//
// A missing catalog is NOT an error. A clean clone has no Program/Lang at all
// (it is gitignored, and lives in a separate private repository), and it must
// still build -- producing a Ukrainian-only exe rather than a build failure.
//
// Usage: node tools/lang/embed.js
// Exit code: 0 normally, 1 if a catalog exists but is unusable.

const fs = require('fs');
const path = require('path');

const EMBEDDED = ['uk', 'en'];
const ROOT = path.join(__dirname, '..', '..');
const LANG_DIR = path.join(ROOT, 'Program', 'Lang');
const RC_PATH = path.join(ROOT, 'Program', 'lang.rc');

const lines = [
  '// Generated by tools/lang/embed.js -- do not edit by hand.',
  '// Paths are relative to this file, which lives in Program\\.',
  '',
];

const embedded = [];
for (const code of EMBEDDED) {
  const file = path.join(LANG_DIR, `${code}.json`);
  if (!fs.existsSync(file)) continue;

  // Parse it: linking a catalog that is not valid JSON, or that declares a
  // different locale than its filename, would produce an exe that silently
  // ignores it at runtime. Fail the build here instead.
  let doc;
  try {
    doc = JSON.parse(fs.readFileSync(file, 'utf8').replace(/^﻿/, ''));
  } catch (e) {
    console.error(`ERROR: ${code}.json is not valid JSON: ${e.message}`);
    process.exit(1);
  }
  if (doc.locale !== code) {
    console.error(`ERROR: ${code}.json declares locale "${doc.locale}"`);
    process.exit(1);
  }

  lines.push(`LANG_${code.toUpperCase()} RCDATA "Lang\\\\${code}.json"`);
  embedded.push(code);
}

if (embedded.length === 0) {
  lines.push('// No catalogs present -- Ukrainian-only build.');
}

fs.writeFileSync(RC_PATH, lines.join('\r\n') + '\r\n', 'utf8');
console.log(`lang.rc written: ${embedded.length ? embedded.join(', ') : 'no catalogs'}`);
