'use strict';

// Generates the ECDSA P-256 keypair used to sign community language catalogs.
// Run ONCE. The private key must never enter the repository tree -- not this
// one, and not the private catalog repository either.
//
// Usage: node tools/lang/keygen.js [path-to-private-key.pem]
//        default: %USERPROFILE%\.myhomelib\lang-signing-key.pem
//
// Prints the public key as a Pascal constant to paste into
// Program/Units/unit_LangSignature.pas.
//
// Losing this key means: new keypair, new constant, new build, and every
// community catalog re-signed. Back it up offline.

const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');

const DEFAULT_KEY = path.join(os.homedir(), '.myhomelib', 'lang-signing-key.pem');
const target = process.argv[2] || DEFAULT_KEY;

if (fs.existsSync(target)) {
  console.error(`ERROR: ${target} already exists. Refusing to overwrite it.`);
  console.error('Generating a new key invalidates every signature made with the old one.');
  process.exit(1);
}

const { privateKey, publicKey } = crypto.generateKeyPairSync('ec',
  { namedCurve: 'prime256v1' });

fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target,
  privateKey.export({ type: 'pkcs8', format: 'pem' }), { mode: 0o600 });

// The 'jwk' export gives the raw affine coordinates, base64url-encoded, which
// is exactly the X||Y pair CNG's BCRYPT_ECCPUBLIC_BLOB wants after its header.
// Going through the DER SubjectPublicKeyInfo instead would mean parsing ASN.1
// to reach the same 64 bytes.
const jwk = publicKey.export({ format: 'jwk' });
const xy = Buffer.concat([
  Buffer.from(jwk.x, 'base64url'),
  Buffer.from(jwk.y, 'base64url'),
]);

if (xy.length !== 64) {
  console.error(`ERROR: expected 64 public key bytes, got ${xy.length}`);
  process.exit(1);
}

const rows = [];
for (let i = 0; i < 64; i += 8) {
  const row = [...xy.subarray(i, i + 8)]
    .map(b => '$' + b.toString(16).toUpperCase().padStart(2, '0'))
    .join(', ');
  rows.push('    ' + row + (i + 8 < 64 ? ',' : ''));
}

console.log(`Private key written to ${target} (mode 0600). Back it up offline.`);
console.log('');
console.log('Paste into Program/Units/unit_LangSignature.pas:');
console.log('');
console.log('  // ECDSA P-256 public key, X||Y. Generated by tools/lang/keygen.js.');
console.log('  LANG_PUBLIC_KEY: array [0 .. 63] of Byte = (');
console.log(rows.join('\n'));
console.log('  );');
