// generate_rc.js — Generate MHLIcons.rc from PNG files
// Mirrors ELN3's generate_icon_resources.py approach

const fs = require('fs');
const path = require('path');

// Icon names per collection (must match dm_Images.pas constants)
const TOOLBAR_ICONS = {
  0: 'book-read',
  1: 'send-to-device',
  2: 'add-to-download',
  3: 'alphabet-cyrillic',
  4: 'alphabet-latin',
  6: 'collection-select',
  7: 'select-all',
  8: 'collapse-expand',
  10: 'tree-table-mode',
  12: 'hide-deleted',
  13: 'local-only',
  14: 'info-panel',
  15: 'add-to-favorites',
  17: 'settings',
  26: 'help'
};

const MENU_ICONS = {
  0: 'book-delete',
  1: 'collection-new',
  2: 'collection-delete',
  3: 'collection-properties',
  7: 'send-to-device',
  8: 'import',
  9: 'sync',
  11: 'settings',
  12: 'book-read',
  13: 'add-to-favorites',
  17: 'help',
  18: 'import',
  20: 'add-to-download',
  21: 'remove-from-group',
  23: 'copy-to-collection',
  24: 'select-all',
  27: 'collection-select',
  29: 'script',
  30: 'rating',
  31: 'copy-to-clipboard',
  32: 'deselect-all',
  33: 'exit',
  35: 'go-to-author'
};

const DOWNLOAD_ICONS = {
  1: 'play',
  2: 'stop',
  3: 'move-first',
  4: 'move-up',
  5: 'move-down',
  6: 'move-last',
  7: 'delete',
  8: 'save',
  9: 'clear'
};

function sanitizeName(name) {
  return name.replace(/-/g, '_').toUpperCase();
}

function generateSection(theme, collection, icons, size) {
  const lines = [];
  const seen = new Set();
  for (const [idx, name] of Object.entries(icons)) {
    const resName = `${theme}_${collection}_${sanitizeName(name)}`;
    if (seen.has(resName)) continue; // skip duplicate resource names (e.g. import at idx 8 and 18)
    seen.add(resName);
    const filePath = `${theme === 'LIGHT' ? 'Light' : 'Dark'}\\png\\${name}_${size}.png`;
    lines.push(`${resName} RCDATA "${filePath}"`);
  }
  return lines;
}

let rc = [];
rc.push('// MHLIcons.rc - Resource script for MyHomeLib themed icons');
rc.push('// Auto-generated by generate_rc.js');
rc.push('');

for (const theme of ['LIGHT', 'DARK']) {
  rc.push(`// === ${theme} THEME ===`);
  rc.push('');
  rc.push(`// Toolbar (32px)`);
  rc.push(...generateSection(theme, 'TOOLBAR', TOOLBAR_ICONS, 32));
  rc.push('');
  rc.push(`// Menu (24px)`);
  rc.push(...generateSection(theme, 'MENU', MENU_ICONS, 24));
  rc.push('');
  rc.push(`// Download (24px)`);
  rc.push(...generateSection(theme, 'DOWNLOAD', DOWNLOAD_ICONS, 24));
  rc.push('');
}

fs.writeFileSync(path.join(__dirname, 'MHLIcons.rc'), rc.join('\n') + '\n');
console.log('Generated MHLIcons.rc');
